### ISSUE TITLE
Does not pick up browser locale settings anymore

### ISSUE THREAD

**Issue by backbone87** [moment/luxon#1000]
**Describe the bug**
Luxon 2 does not pick up the browser locale anymore.
- Settings.defaultLocale is `null`
- systemLocale had its detection functionality removed

**To Reproduce**
Use a non-English browser and output a DateTime.toLocaleString() without setting any locales.

**Actual vs Expected behavior**
Expected: The date is output in the browser language. (This works in Luxon ^1)
Actual: The date is output in en-US.

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Chrome92
- Luxon version: 2.0.1
- Your timezone: Europe/Berlin

**Additional context**
the detection was removed here:
https://github.com/moment/luxon/commit/6bb7488b8a2869c6f1b70ca7fac55f9e2e439485#diff-572c92ef1c461030cf7e47772319dd3db1ec2b880dadca7f88a3d9cee8e22ca3L46-L50

**Comment by sceee** [comment]
I can confirm this and I already wondered whether this was a breaking change in v2 but according to the docs ( https://moment.github.io/luxon/#/intl?id=out-of-the-box-behavior ) and the changelog it should still behave as we expect - the browser's language is used to determine the default locale automatically.

So it definitely seems to be a bug.

**Comment by johannesd** [comment]
Using luxon for the first time; after two hours of debugging finally landed here. Please fix :)

**Comment by icambron** [comment]
Fixed in 2.0.2

**Comment by rbluethl** [comment]
This doesn't seem to work in Luxon 2.3.0. The `defaultLocale` is null and `DateTime.local().toLocaleString()` prints the date in en-US.

**Comment by robincsamuel** [comment]
@icambron Same issue on luxon 3.0.1. `navigator.language` prints the correct locale but luxon is still using `en-GB`.

**Comment by Venators** [comment]
The issue still seems to be present in v3.0.3 as well - my local is en-NZ (when checked with `navigator.language`) but Luxon is using `en-GB` (when checked with `DateTime.local()`)

**Comment by robincsamuel** [comment]
@icambron Just checking if you got a chance to check this issue. Can we please re-open this issue?

**Comment by icambron** [comment]
en-GB` doesn't appear anywhere in Luxon's source code, so I don't think it's something weird Luxon is doing.

I can't reproduce this in Chrome either:

```js
navigator.language //=> 'en-NZ'
luxon.DateTime.now().locale // => 'en-NZ'
```

Can you open a new ticket with more details?

**Comment by robincsamuel** [comment]
I'm not sure what other details would help. 

I just visited https://moment.github.io/luxon and opened the console and executed the following.

<img width="599" alt="Screenshot 2022-12-23 at 12 45 50 AM" src="https://user-images.githubusercontent.com/4545992/209209887-6ab909d6-e4e2-458c-baff-6298cc4ccd13.png">

**Comment by dasa** [comment]
This seems to be how it gets the default locale:
https://github.com/moment/luxon/blob/f9917c4a656ea715e0aae9de8022c64933826964/src/impl/locale.js#L59

What do you get for `new Intl.DateTimeFormat().resolvedOptions().locale` and `navigator.languages`?

**Comment by robincsamuel** [comment]
@dasa 

```javascript
navigator.languages
// => ['en-US']

new Intl.DateTimeFormat().resolvedOptions().locale; 
// => 'en-GB'
```
